//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleAspNetApp
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label Label1;
    }
}
